### PR TITLE
Fix Leaderboard error 500

### LINKED ISSUE #19: Can't get leaderboards
`Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: 'POST https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/leaderboards/type/global/stat/br_placetop1_pc_m0_p10/window/weekly?ownertype=1&itemsPerPage=50` resulted in a `500 Internal Server Error' response: {"errorCode":"errors.com.epicgames.common.server_error","errorMessage":"Sorry an error occurred and we were unable to re (truncated...) in C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), in C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113`

### PR DESCRIPTION
**Pull request by Krokit**
Added user in_app_id
Added new get request for leaderboard users
Changed build versions
Fixed leaderboard error 500 (fixed #19 )

Epic Games know how to break something 😅

### CODE REVIEW

**Comment by Tustin** [comment]
This is great; thank you! How exactly did you find out what they changed? Last I checked, the mobile apps didn't have leaderboards and the Windows builds have certificate pinning built into the anti-cheat.

**Comment by Krokit** [comment]
@Tustin I saw that leaderboard request is json and there were some json data, data was ids of players. I take 1 id from the leaderboard request and i found that this id was taken from the cohort request and after some checks, i try with postman to check is everting okay i apply a patch to this problem.  I'm waiting for my friend to give me access to an account which has Save The World and i will check is any available api. :)

**Comment by NeVeR2TrY** [comment]
@Krokit 
"Class 'Fortnite\LeaderboardNotFoundException' not found"

copied the changes but still same error

**Comment by NeVeR2TrY** [comment]
@Krokit 
how to get data for example
All Platforms?
or All Time not for the current season ?
All Modes?

**Comment by NeVeR2TrY** [comment]
@Krokit any idea?

**Comment by Krokit** [comment]
@NeVeR2TrY  I will check it. 😄

**Pull request merged**
